# Generated by Django 3.1 on 2021-01-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210116_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default='0', editable=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default='1000', editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default='0', editable=False),
        ),
    ]
