# Generated by Django 3.1 on 2021-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210116_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
    ]
