# Generated by Django 3.1 on 2021-01-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
        ('main_app', '0009_auto_20210116_2059'),
    ]

    operations = [
    ]
