# Generated by Django 3.1 on 2021-01-18 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210118_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_answer',
            name='question',
        ),
        migrations.AddField(
            model_name='like_answer',
            name='answer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.answer'),
            preserve_default=False,
        ),
    ]
