# Generated by Django 3.1 on 2021-01-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210118_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Garden', 'Garden'), ('Other', 'Other')], max_length=24),
        ),
    ]
